apiVersion: v1
kind: Service
metadata:
  name: runtime-operator
  namespace: {{ .Release.Namespace }}
  labels:
    wasmcloud.com/name: runtime-operator
    {{- include "runtime-operator.labels" . | nindent 4 }}
spec:
  selector:
    wasmcloud.com/name: runtime-operator
  type: {{ .Values.operator.service.type }}
  ports: 
    - port: {{ .Values.operator.service.port }}
      targetPort: https
      protocol: TCP
      name: https