# Based on https://github.com/authzed/actions/blob/main/go-mod-tidy/action.yaml
name: "Go - Lint"
description: |
  This action runs `go mod tidy` & golangci-lint over the working tree and then verifies
  that there are no differences from running the tool.
inputs:
  working-directory:
    description: "The directory with the root of the project"
    default: "."
    required: false
  timeout:
    description: "The timeout for the golangci-lint step"
    default: "5m"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Run Go Mod Tidy"
      shell: "bash"
      working-directory: "${{ inputs.working-directory }}"
      run: "go mod tidy"
    - name: "Verify Go Mod Tidy"
      uses: "wasmCloud/runtime-operator/.github/actions/no-diff@main"
      with:
        fixup-command: "go mod tidy"
    - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        version: v2.4
        working-directory: "${{ inputs.working-directory }}"
        args: --verbose --path-prefix "${{ inputs.working-directory }}" --timeout ${{ inputs.timeout }}
